### ISSUE TITLE
botocore.exceptions.NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by dageita** [koushal95/Amazon-EC2-Spot-Price-Analysis#1]
Hi, thanks for your great work, but I come across a credential problem when execute spot_price_predict.py, can you help me?

Traceback (most recent call last):
  File "spot_price_predict.py", line 121, in <module>
    df = wrapper(['m4.large', 'm4.xlarge'],['Linux/UNIX (Amazon VPC)'], 'us-west-2')
  File "spot_price_predict.py", line 35, in wrapper
    }, ''))
  File "spot_price_predict.py", line 23, in handler
    MaxResults=10000
  File "/python3.5/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/python3.5/site-packages/botocore/client.py", line 573, in _make_api_call
    operation_model, request_dict, request_context)
  File "/python3.5/site-packages/botocore/client.py", line 592, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/python3.5/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/python3.5/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/python3.5/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/python3.5/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/python3.5/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/python3.5/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/python3.5/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/python3.5/site-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/python3.5/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by dageita** [comment]
Well, that's a stupid question, I found the solution in here:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/quickstart.html
